modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Berries-and-More/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/berries-and-more"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512, giok3r"

[[mods]]
    modId="berriesandmore"
    version="${file.jarVersion}"
    displayName="Berries and More"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Berries-and-More/1.20.x/update.json"
    description='''
    More berries and food items
    '''

[[dependencies.berriesandmore]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.berriesandmore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.berriesandmore]]
    modId="silentlib"
    mandatory=true
    versionRange="[8,)"
    ordering="NONE"
    side="BOTH"
